### ISSUE TITLE
Using native I2C bus on MKR1000

### ISSUE THREAD

**Issue by Denibel** [avishorp/TM1637#12]
- Your library asks for two of the eigth general purpose I/O pins which, I suppose, will be used as a _software emulated_ I2C port. Is there any way to use the _native_ I2C port of the processor, on pin labelled "SCL" and "SDA" which do not have a "pin" number in the arduino sense, but are pins 13 and 14 on the MKR1000 socket and pins 38, 39 of the Atmel ATSAMW25H18 processor.

- I suppose also that there are some other Arduino boards with native I2C. Using it will be faster and will save other GP I/Os ...

**Comment by avishorp** [comment]
Hi
You are right, I'm using software emulated I2C. Arduino and probably all
boards of this kind have hardware I2C, but currently I'm not planning to
port the library to use it. The amount of communication between the
processor and the display driver is very small, it's not going to provide
any meaningful speedup.

Avishay

2016-08-03 17:30 GMT+03:00 Denibel <notifications@github.com>:
