### ISSUE TITLE
documentation vs example on setBrightness?

### ISSUE THREAD

**Issue by treii28** [avishorp/TM1637#13]
Why does your example code show:

 setBrightness(0x0f) // 0x0f = 15

while the documentation says it is supposed to be a value from 0 to 7? What is the actual range?

**Comment by avishorp** [comment]
The controller chip supports 7 brightness levels. The 4th (MSB) bit of the brightness parameter is an ON/OFF bit (thus making the actual brightness range from 8 to 15).
Thanks for pointing that out! I'll fix it in the next release.
