### ISSUE TITLE
Digispark ATtiny85

### ISSUE THREAD

**Issue by aliceand** [avishorp/TM1637#15]
I've used your code on a NodeMCU, but I'm having trouble on a Digispark ATtiny85.  I'll be debugging this weekend, but in the meantime I thought I'd ask if you've have the opportunity to test on the digispark attiny85 hardware.  

There are two form factors; a male usb header, and a female micro usb header.  I have the microusb header like this one:
https://www.aliexpress.com/item/Mini-ATTINY85-Micro-USB-Development-Board-for-Digispark-Kickstarter/32658933669.html?spm=2114.13010608.0.0.vQXWLx

**Comment by avishorp** [comment]
Unfortunately I don't have this hardware platform so I won't be able to help you. If you do find a bug, please issue a pull request.
Avishay
