### ISSUE TITLE
Incorrect use of GPIOs

### ISSUE THREAD

**Issue by msloth** [avishorp/TM1637#19]
Hey, thanks for the lib. However, you are using the incorrect functions for the GPIOs: instead of using the functionality for setting pins high/low, you are setting them as input/output. This should only be done for the SDA-pin when waiting for an ACK. I think the arduino-functions for setting the output low or high is `digitalWrite()`.

**Comment by msloth** [comment]
Might be the cause of #17

**Comment by avishorp** [comment]
The reason for using this method is the external pull-up that exists on SDA & SCL. When the the line has to be pulled low, it is set as output. In other cases, it is set as input, allowing the external pull-up resistor to set the logic level to 'high' or any other potential bus user to pull the line to a low state.
