### ISSUE TITLE
Reimplementation to get rid of small annoyances

### ISSUE THREAD

**Issue by janezd** [avishorp/TM1637#21]
Not really an issue, I'm just abusing this to send you a message. :)

First, thanks for the library. I used it a lot.

It however has several small glitches that I tried to fix, like setBrightness not taking effect immediately, not working with negative numbers, the colon at the center of the display can't be set without setting the second digit etc. I found that improving this would be difficult (or sometimes impossible) because the library does not store the content of the display. I ended up basically reimplementing the library, keeping only the low-level functions for communication with TM1637.

I also changed the behaviour and/or signature of several methods, I removed some and added some, so my version is no longer compatible with your original. Thus I renamed it, so I can have both and still use my older projects (and project from others).

I'd create a pull request here, but my code is too different and I don't even know whether you want this functionality at all. So I'm writing this just to inform you of my fork, https://github.com/janezd/Led7Segment from which you can perhaps backport something useful to your original library. In particular, `showNumber` may be interesting.

**Comment by avishorp** [comment]
Thanks, janezd, but I can't merge such changes into the current code, because it will break current API and behavior. You may want to list your library on [this page](http://playground.arduino.cc/Main/InterfacingWithHardware#Output).
