### ISSUE TITLE
Clocking out the LSB first?

### ISSUE THREAD

**Issue by mcu7** [avishorp/TM1637#24]
This is a clean, well-written library. But one thing I do not understand.

While sending data to TM1637, is there a reason you are clocking out the LSB first, and not the MSB? I was under the impression that the TM1637 interface is essentially I2C, which clocks out the MSB first.

```
// 8 Data Bits
  for(uint8_t i = 0; i < 8; i++) {
    // CLK low
    pinMode(m_pinClk, OUTPUT);
    bitDelay();

	// Set data bit
    if (data & 0x01)
      pinMode(m_pinDIO, INPUT);
    else
      pinMode(m_pinDIO, OUTPUT);

    bitDelay();

	// CLK high
    pinMode(m_pinClk, INPUT);
    bitDelay();
    data = data >> 1;
  }

```

Have you tested this code with an actual TM1637? I assume that you have.

**Comment by avishorp** [comment]
I don't know if I2C dictates the order of bits, anyway this is how this particular chip works.
