### ISSUE TITLE
Bad owerflow math

### ISSUE THREAD

**Issue by Youda** [avishorp/TM1637#28]
function SetTimer	  
Was:
Clock = (hours * 3600) + (minutes * 60) + (seconds % 60);
Should be:
Clock = (hours * 3600) + ((minutes % 60) * 60) + (seconds % 60);
because otherwise input:
T.SetTimer(0, 60, 0);
returns 
2 hours 0 minutes 0 seconds

**Comment by avishorp** [comment]
No function SetTimer in this project.... you probably missed the right repository.
