### ISSUE TITLE
Default bitDelay() of 50us is too fast for some devices.

### ISSUE THREAD

**Issue by MaximumOctopus** [avishorp/TM1637#43]
The default bitDelay() of 50 microseconds is too fast for some TM1637-based devices.

I suggest a lower default, and perhaps comments in the code/example to suggest using faster values if the device can take it.

Tested using generic device off ebay. Genuine Arduino Micro and Uno, and RFDuino Duemilanove.

**Comment by avishorp** [comment]
It has been changed to 100uS in the master branch.
