### ISSUE TITLE
Serial.parseInt(); stops. Cannot send input to serial monitor via keyboard.

### ISSUE THREAD

**Issue by EbaRednaxela** [avishorp/TM1637#44]
After running this sample code I got from youtube, the serial monitor stops accepting input in the serial monitor:

`#define TimeInSeconds(_time_) ((_time_ / 1000) % 60)`
`#define TimeInMinutes(_time_) (((_time_ / 1000) / 60) % 60)`

`#include <Arduino.h>`
`#include <TM1637Display.h>`

`// Constants`

`const uint8_t OFF[] = {0, 0, 0, 0};`
`const uint8_t PLAY[] = {B01110011, B00111000, B01011111, B01101110};`

`int serialInput = 0;`

`unsigned long timeLimit = 3600000;`

`TM1637Display display(2, 4);`

`// Setup`
`void setup() {`
`  Serial.begin(9600);`
`  delay(5000);`
`  display.setBrightness(0x0c);`
`  display.setSegments(OFF);`
`}`

`// Main loop`
`void loop() {`
` if(Serial.available()){`
`    serialInput = Serial.parseInt();`
    
`    switch(serialInput){`
`      case 1:`
`          Serial.println("Ready For Station One.");`
`        break;`
`      case 2:`
`          Serial.println("Ready For Station Two.");`
`        break;`
`      case 3:`
`          Serial.println("Ready For Station Three.");`
`        break;`
`      case 4:`
`          Serial.println("Ready For Station Four.");`
`        break;`
`      }`
`    }`
`  countdown();`
`}`

`void countdown() {`
`  unsigned long timeRemaining = timeLimit - millis();`

`  while(timeRemaining > 0) {`

`    int seconds = TimeInSeconds(timeRemaining);`
`    int minutes = TimeInMinutes(timeRemaining);`

`    display.showNumberDecEx(seconds, 0, true, 2, 2);`
`    display.showNumberDecEx(minutes, 0x80>>3, true, 2, 0);`

`    timeRemaining = timeLimit - millis();`
`  } `
`}`

Is there anything wrong with the code implementation? Or I'm just using it incorrectly? Thanks in advance for the correction.

**Comment by avishorp** [comment]
Not a library issue.
