### ISSUE TITLE
how to display single dot i.e decimal point?

### ISSUE THREAD

**Issue by somtips** [avishorp/TM1637#49]

**Comment by Mr-Auto** [comment]
Same problem
No problem with turning on the colon, but the dots don't work

Also, 
`For displays with dots between each digit:
* 00.00 (0b01000000)`
`For displays with just a colon:
* 00:00 (0b01000000)`
how this suppostu work?

**Comment by avishorp** [comment]
Some modules do not wire the decimal dots at all, only the colon, so no
software solution here.

‫בתאריך יום א׳, 24 במרץ 2019 ב-17:47 מאת ‪Mr-Auto‬‏ <‪
notifications@github.com‬‏>:‬
