### ISSUE TITLE
decimal dot

### ISSUE THREAD

**Issue by honzakrivohlavy** [avishorp/TM1637#5]
// note to .cpp file:
//
//      A
//     ---
//  F |   | B
//     -G-
//  E |   | C
//     ---  . = X
//      D
//           

// .cpp added code for to show a decimal dot: 
void TM1637Display::showNumberDecDot(int num, bool leading_zero, uint8_t length, uint8_t pos, int decimal_dot_place)
{
    uint8_t digits[4];
    const static int divisors[] = { 1, 10, 100, 1000 };
    bool leading = true;

```
for(int8_t k = 0; k < 4; k++) {
    int divisor = divisors[4 - 1 - k];
    int d = num / divisor;

    if (d == 0) {
      if (leading_zero || !leading || (k == 3))
        {
     digits[k] = encodeDigit(d);
     if (decimal_dot_place==k)
     digits[k] += 0b10000000;
    }
      else
        digits[k] = 0;
     if (decimal_dot_place==k)
     digits[k] += 0b10000000;
    }



    else {
        digits[k] = encodeDigit(d);
        num -= d * divisor;
        leading = false;
     if (decimal_dtot_place==k)
     digits[k] += 0b10000000;
    }
}

setSegments(digits + (4 - length), length, pos);
```

}

//.h file description added:
void showNumberDecDot(int num, bool leading_zero = false, uint8_t length = 4, uint8_t pos = 0, int decimal_dot_place = 5);
  //! @param decimal_dot_place  - show decimal dot on selected segment

**Comment by nathan30** [comment]
It's works, thanks a lot ! You've juste made a mistake at this line "if (decimal_dtot_place==k)" it's "decimal_dot_place"

**Comment by avishorp** [comment]
Please check the latest version of the library, it contains support for the dots.

Avishay
