### ISSUE TITLE
Test case fail "expect 04__"

### ISSUE THREAD

**Issue by dwillmore** [avishorp/TM1637#52]
The test sketch line:
display.showNumberDec(4, true, 2, 2); // Expect: 04__

Fails to display properly.  Instead __04 displays.

Arduino 1.8.8. Linux x86_64 Fedora 29.  Library version 1.2.0 installed via the Library Manager.  Board esp8266 based "NodeMCU 1.0 (ESP-12E Module)" supported from "esp8266 by ESP8266 Community" version 2.5.0.

Let me know if you can't reproduce.

**Comment by avishorp** [comment]
Actually, the comment is incorrect. The number shown on the display is the expected one. The comment has been fixed.

**Comment by dwillmore** [comment]
That works, too! :)  thank you!
