### ISSUE TITLE
Including wrong header file when using Library Manager for Arduino

### ISSUE THREAD

**Issue by nefingar** [avishorp/TM1637#54]
I encountered a little error while importing the library using the default Arduino Library Manager.
If you install and include the library it said "#include <TM1637.h>" but the header file is called TM1637Display.h

It can be fixed by editing the library.properties file and change the line "includes=TM1637.h" with "includes=TM1637Display.h"

After that reopen the Arduino Project and include the library again, and it will call the correct header file.

**Comment by avishorp** [comment]
Thank you for reporting. Fixed.
