### ISSUE TITLE
read button

### ISSUE THREAD

**Issue by Persp0lisy** [avishorp/TM1637#60]
hi,is that possible to read a key(high or low) by tm1637 using this library?
if answer is no,is that possible to add this to library?
thank you

**Comment by avishorp** [comment]
This functionality is not currently implemented, and I have no plan to do
so.

Avishay

בתאריך יום ה׳, 5 בדצמ׳ 2019, 10:46 אחה״צ, מאת Persp0lisy ‏<
notifications@github.com>:
