### ISSUE TITLE
MKR1010 pinMode INPUT doesn't work

### ISSUE THREAD

**Issue by szaiftamas** [avishorp/TM1637#63]
I tried this library, but doesn't work with MKR1010. 
I use the pin A3 and A4 to CLK and DIO, and the display module include 10K pull up resistor and 100p capacitor on both channel.
I verified the CLK and DIO with oscilloscope, and it is not able to pull up to Vcc in this speed.
I have two choice, one of them to decrease the speed or change the pinMode to digitalWrite.
The digitalWrite solved our problem.

**Comment by avishorp** [comment]
You shouldn't change the pinMode to digitalWrite, because this line can be driven by the display and it must be 3-state. You can either make the bit delay longer and/or add a 4.7k resistor in parallel to the existing one (from VCC to the pin).
