### ISSUE TITLE
Little issue showing colon

### ISSUE THREAD

**Issue by alterm26** [avishorp/TM1637#64]
I found a little issue with the library. When you try to show num = 0 without leading zeros, with something like this:
`display.showNumberDecEx(hour, dospuntos, false, 2, 0);`
colon is not longer shown.
To solve this I added  the following in line 148 of TM1637Display.cpp:
` if(dots != 0)    
		{
			showDots(dots, digits);
		}`
I used the library with a MSP430G2553 and it works fine. It's really very versatile.

**Comment by SuperLeaf8** [comment]
this literally fixed the issue im having, could it be put in the main code?
