### ISSUE TITLE
colon display when not showing leading zeros and the value is 0

### ISSUE THREAD

**Issue by jan-gerard** [avishorp/TM1637#65]
I use a 4-digid display with a single colon in the center. The colon is not displayed when I have the leading zeros parameter set to false, and the value is zero.
```
red.showNumberDecEx(hour(), 0b11111111*(second()%2), false, 2, 0);
red.showNumberDec(minute(), true, 2, 2);
```
It works correctly for any other value than zero, but if `hour()` in the above example is 0, the colon does not show. This seems to me like a small bug.

**Comment by avishorp** [comment]
Fixed, thanks for reporting.
