### ISSUE TITLE
Can we combine number and letter like "123H"?

### ISSUE THREAD

**Issue by HubKing** [avishorp/TM1637#76]
There is a function for displaying numbers `showNumberDec`, and a function for displaying arbitrary segments `setSegments`, but what if I want to display both (but at different positions), like "123H"?

**Comment by avishorp** [comment]
showNumberDec should be considered a helper function, making it easy to display numbers. With setSegments you can display anything you want. You can also use a combination of both - showNumberDec to display the number part and setSegments to set only the non-numeric digits.
