### ISSUE TITLE
use tm1637 with pcf8574 port expander

### ISSUE THREAD

**Issue by alirezaimi** [avishorp/TM1637#84]
Hi
How can i use tm1637 7segment with pcf8574 port expander ?

PCF8574 expander(0x20, 4, 5);  // esp8266 nodemcu and all Ax pins are Grounded
TM1637Display display(P4, P5);

and when i connect pins to 4 and 5 of esp8266 board its work !

**Comment by avishorp** [comment]
Sorry I don't know how to use the PCF8574, but you should probably replace the pinMode and digitalWrite commands in the source code to their equivalent function for controlling the expander pins.

**Comment by alirezaimi** [comment]
Thanks, but I did this and edit pcf lib code and not work .

**Comment by aschewski** [comment]
@alirezaimi: I have the same challenge. Have you found a solution in the meantime to use tm1637 with pcf8574 port expander?
